apiVersion: v1
kind: Service
metadata:
  name: python-on-kube-service
spec:
  selector:
    app: python-on-kube
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: NodePort


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-on-kube
  labels:
    app: python-on-kube
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python-on-kube
  template:
    metadata:
      labels:
        app: python-on-kube
    spec:
      containers:
      - name: python-on-kube
        image: python-on-kube:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.1"


# ---
# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: python-on-kube
# spec:
#   replicas: 4
#   template:
#     metadata:
#       labels:
#         app: python-on-kube
#     spec:
#       containers:
#       - name: python-on-kube
#         image: python-on-kube:latest
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 5000
#         resources:
#           limits:
#             memory: 512Mi
#             cpu: "1"
#           requests:
#             memory: 256Mi
#             cpu: "0.1"